### ISSUE TITLE
Change the type of `bodyIdx` and `percent` to `uint`

### ISSUE THREAD

**Issue by quangkeu95** [flashbots/mev-share-node#14]
# Describe the issue
Since `bodyIdx` is the index value and `percent` is number of percent relative to 100 scale, could we use `uint` for them?

```golang
type RefundConstraint struct {
	BodyIdx int `json:"bodyIdx"`
	Percent int `json:"percent"`
}

type RefundConfig struct {
	Address common.Address `json:"address"`
	Percent int            `json:"percent"`
}
```

**Comment by dvush** [comment]
I think moving to uint will not improve safety because actual type is number between 0 and 100 and properties like that are validated separately
